name: HA-Linky-Docker

on:
  schedule:
    - cron: '22 18 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths:
      - 'ha-linky/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}/ha-linky


jobs:
  workflow-call-docker-build-push:
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    uses: ./.github/workflows/docker-build-publish.yml
    with:
      image: ha-linky
